{% set name = "dbt-adapters" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dbt-labs/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5c0f8e34e6531b9d8787a629b7e2b63cb6eb47cc3b5d1c373a05a82fcbc9fda7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  # dbt-common is only from 3.9 to 3.12
  skip: True  # [py<39 or py>312]
  # dbt-common is not avaliable for the s390x platform
  skip: True  # [s390x]

requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - dbt-common >=1.11,<2.0
    - pytz >=2015.7
    - agate >=1.0,<2.0
    - mashumaro >=3.0,<4.0
    # The msgpack pkg needs for "mashumaro[msgpack]>=3.0,<4.0"
    # correct version is msgpack>=0.5.6
    - msgpack-python >=0.5.6
    - protobuf >=3.0,<5.0
    - typing-extensions >=4.0,<5.0

test:
  source_files:
    - tests
  imports:
    - dbt.adapters
  commands:
    - pip check
    - python -m pytest -v tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/dbt-labs/dbt-adapters
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  dev_url: https://github.com/dbt-labs/dbt-adapters
  doc_url: https://docs.getdbt.com/
  summary: The set of adapter protocols and base functionality that supports integration with dbt-core
  description: The set of adapter protocols and base functionality that supports integration with dbt-core

extra:
  recipe-maintainers:
    - conda-forge/dbt
    - thewchan
    - rxm7706
