{% set name = "dbt-adapters" %}
{% set version = "1.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 5b8da1225fdda8f2a7a5ce617e70345fdb63e0e9c3a5c5909281c1bb43f689f5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - dbt-common >=1.13,<2.0
    - dbt-protos >=1.0.291,<2.0
    - pytz >=2015.7
    - agate >=1.0,<2.0
    # The msgpack pkg needs for "mashumaro[msgpack]>=3.9,<3.15"
    # correct version is msgpack>=0.5.6
    - mashumaro >=3.9,<3.15
    - msgpack-python >=0.5.6
    - protobuf >=6.0,<7.0
    - typing-extensions >=4.0,<5.0

test:
  source_files:
    - tests
  imports:
    - dbt.adapters
  commands:
    - pip check
    - python -m pytest -v tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/dbt-labs/dbt-adapters
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  dev_url: https://github.com/dbt-labs/dbt-adapters
  doc_url: https://docs.getdbt.com
  summary: The set of adapter protocols and base functionality that supports integration with dbt-core
  description: The set of adapter protocols and base functionality that supports integration with dbt-core

extra:
  recipe-maintainers:
    - conda-forge/dbt
    - thewchan
    - rxm7706
