{% set name = "dbt-adapters" %}
{% set version = "1.13.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dbt_adapters-{{ version }}.tar.gz
  sha256: 7498c6e8d0a3b14a903564e80b509dbe3c3453acd3b251bf620b551dc1ab1d47

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - dbt-common
    - pytz
    - agate
    - mashumaro
    - protobuf
    - typing_extensions
    # for mashumaro[msgpack]
    - msgpack-python

test:
  imports:
    - dbt.adapters
  commands:
    - pip check
  requires:
    - python
    - pip

about:
  home: https://github.com/dbt-labs/dbt-adapters
  summary: The set of adapter protocols and base functionality that supports integration with dbt-core
  license: Apache-2.0
  license_file: LICENSE

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/63495
    reason: Dependency for dbt-core
  recipe-maintainers:
    - ianaobi
  recipe-maintainers:
    - conda-forge/dbt
    - thewchan
    - rxm7706
