{% set name = "dbt-adapters" %}
{% set version = "1.24.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 87de096a0d5b219905f1079b002f13e3447ffb63558f4f3c5b7278670d198acb

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - dbt-common >=1.36,<2.0
    - dbt-protos >=1.0.291,<2.0
    - pytz >=2015.7
    - agate >=1.0,<2.0
    # The msgpack pkg needs for "mashumaro[msgpack]>=3.9,<3.18"
    # correct version is msgpack>=0.5.6
    - mashumaro >=3.9,<3.18
    - msgpack-python >=0.5.6
    - protobuf >=6.0,<7.0
    - typing-extensions >=4.0,<5.0

# E   jinja2.exceptions.TemplateNotFound: 'apply_grants.sql' not found in search path: 'src/dbt/include/global_project/macros/adapters'
{% set deselect_tests = " --deselect=tests/unit/test_base_adapter.py::TestGrantsMacroQuotesGrantees::test_grant_macro_does_not_quote_grantees" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/unit/test_base_adapter.py::TestGrantsMacroQuotesGrantees::test_revoke_macro_quotes_grantees" %}
test:
  source_files:
    - tests
  imports:
    - dbt.adapters
  commands:
    - pip check
    - python -m pytest -v tests {{ deselect_tests }}
  requires:
    - pip
    - pytest

about:
  home: https://github.com/dbt-labs/dbt-adapters
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  dev_url: https://github.com/dbt-labs/dbt-adapters
  doc_url: https://docs.getdbt.com
  summary: The set of adapter protocols and base functionality that supports integration with dbt-core
  description: The set of adapter protocols and base functionality that supports integration with dbt-core

extra:
  recipe-maintainers:
    - conda-forge/dbt
    - thewchan
    - rxm7706
