{% set name = "dbt-adapters" %}
{% set version = "1.16.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: ac6d2f880a70608374c8ecaa8d0b67c56fe6f5b744495df6c5cb54ba8813b3a2
  patches:
    - patches/0001-update-protobuf-version.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<39]

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - dbt-common >=1.13,<2.0
    - dbt-protos >=1.0.291,<2.0
    - pytz >=2015.7
    - agate >=1.0,<2.0
    - protobuf >=5.0,<7.0
    - typing-extensions >=4.0,<5.0
    # The msgpack pkg needs for "mashumaro[msgpack]>=3.9,<3.15"
    # correct version is msgpack>=0.5.6
    - mashumaro >=3.9,<3.15
    - msgpack-python >=0.5.6

test:
  source_files:
    - tests
  imports:
    - dbt.adapters
  commands:
    - pip check
    - python -m pytest -v tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/dbt-labs/dbt-adapters
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  dev_url: https://github.com/dbt-labs/dbt-adapters
  doc_url: https://docs.getdbt.com
  summary: The set of adapter protocols and base functionality that supports integration with dbt-core
  description: The set of adapter protocols and base functionality that supports integration with dbt-core

extra:
  recipe-maintainers:
    - conda-forge/dbt
    - thewchan
    - rxm7706
